# -*-coding:utf-8-*-

# coder: Jiawen Zhu
# date: 2019.6.9
# state: half modified

# net architecture
architecture: lenet

# log and checkpoint
use_checkpoint: False
data_path: ./datasets/cifa10/
ckpt_path: ./exp_output/cifa10_lenet/
ckpt_name: lenet
# lenet没有预训练模型
if_pretrain: True

# datasets
num_classes: 10
dataset: cifar10
aug_padding: 4

# training parameters
train_show_freq: 300
use_gpu: True
input_size_w: 32
input_size_h: 32
epochs: 60
batch_size: 128
test_batch: 200
# 2 epoches
eval_freq: 2
workers: 4

# optimizer
optimize:
  momentum: 0.9
  weight_decay: 0.0001
  # sgd的一种改进
  nesterov: True

# regularization
# todo
mixup: False
mixup_alpha: 0.4

augmentation:
  # normalize  [- mean / std]
  normalize: True
  # padding=4
  # todo: it has the same w and h
  random_crop: True
  random_horizontal_filp: True
  # ?
  cutout: False
  # ?
  holes: 1
  # ?
  length: 8

# learning rate scheduler
lr_scheduler:
  # type: STEP
  type: STEP
  base_lr: 0.01
  # only for STEP
  # todo : sure this can work
  lr_epochs: [100, 150, 200]
  # todo
  lr_mults: 0.1
  min_lr: 0.0
  # only for HTD
  lower_bound: -6.0
  upper_bound: 3.0
