# -*-coding:utf-8-*-

# coder: Jiawen Zhu
# date: 2019.6.9
# state: modified

# net architecture
architecture: alexnet

# log and checkpoint
use_checkpoint: False
data_path: ./datasets/easy/
ckpt_path: ./exp_output/easy_alexnet/
ckpt_name: alexnet
if_pretrain: True

# datasets
num_classes: 3
dataset: easy
aug_padding: 4


# training parameters
train_show_freq: 8
use_gpu: True
# todo: w*h
# lenet的输入尺寸超过48后就很难收敛,调小学习率
input_size_w: 224
input_size_h: 224
epochs: 50
batch_size: 64
test_batch: 64
# 2 epoches
eval_freq: 2
# 读数据时的多进程
workers: 4

# optimizer
optimize:
  momentum: 0.9
  weight_decay: 0.0001
  # sgd的一种改进
  nesterov: True

# regularization
# ?
mixup: False
mixup_alpha: 0.4

augmentation:
  # normalize  [- mean / std]
  normalize: False
  # padding=4
  random_crop: True
  random_horizontal_filp: True
  # ?
  cutout: False
  # ?
  holes: 1
  # ?
  length: 8

# learning rate scheduler
lr_scheduler:
  # type: STEP or COSINE or HTD
  type: STEP
  base_lr: 0.005
  # only for STEP
  lr_epochs: [40, 150, 200]
  lr_mults: 0.1
  # for HTD and COSINE
  # ?
  min_lr: 0.0
  # only for HTD
  # ?
  lower_bound: -6.0
  upper_bound: 3.0 
